senty-upgrade-amount: 3 #amount of sentry upgrade items you need to upgrade
gun-upgrade-amount: 3 #amount of gun turret upgrade items you need to upgrade
manual-upgrade-amount: 3
invading-broadcast: "&9A new war is out there, {0} invaded {1}"


console-armies:
  us:
    core: "100;69;100;world"
    description: "this is a configurable description"
  safezone:
    core: "100;69;150;world" # X, Y, Z, WORLD
    description: "there is no pvp here only peace"
  warzone:
    core: "150;69;150;world" # X, Y, Z, WORLD
    description: "there is pvp here"









menu-gui:
  rows: 3
  title: "&3Menu"

top-army:
  size: 5 #to display top 5 armies
  title: "----------- Top Players -------------"
  line: "&3{0} with a balance of &a{1}"
core-holding:
  minutes: 1
  percentage-money: 10

shop:
  gui-rows: 3
  gui-title: "&aGuiTitle"
  money-not-enough: "You don't have enough money to purchase {0}!"
  success: "You bought {0} successfully"
  products:
    claim-card:
      price: 1000.5
      name: "&3Claim Card"
      slot: 10
      material: PAPER
      glow: true
      payment-method: "army" # YOU CAN DO army or user and anything else gonna be army
      lore:
        - "first lore"
        - "second lore"
    turrets:
      sentry:
        price: 5000
        name: "&3Sentry turret"
        slot: 4
        nbt: "turret-sentry" #do not change that ⚠
        material: GOLD_BLOCK
        glow: false
        lore:
          - "first lore"
          - "second lore"
      sentry-upgrade:
        price: 1000.5
        name: "&3Sentry upgrade item"
        slot: 11
        material: IRON_BLOCK
        glow: false
        nbt: "upgrade-sentry"
        lore:
          - "first lore"
          - "second lore"
      gun-turret:
        glow: true
        name: "&3Gun turret"
        slot: 0
        material: FIREBALL
        nbt: "turret-gun"
        lore:
          - "first lore"
          - "second lore"
      manual-gun:
        glow: true
        name: "&3Manual turret"
        slot: 18
        material: FIREWORK
        nbt: "turret-manual gun"
        lore:
          - "first lore"
          - "second lore"
      manual-upgrade:
        glow: true
        name: "&3Manual Gun upgrade"
        slot: 25
        material: GOLD_AXE
        nbt: "upgrade-manual gun"
        lore:
          - "first lore"
          - "Second lore"
      gun-turret-upgrade:
        price: 1000.5
        name: "&3gun turret upgrade item"
        slot: 20
        material: DIAMOND_AXE
        glow: false
        nbt: "upgrade-gun"
        lore:
          - "first lore"
          - "second lore"





invite:
  durability: 120 #in seconds
